#!/bin/bash -
if [ $# -gt 1 ]
then
    if [ -r ~/quicklisp/local-projects/features.asd -a -r ~/quicklisp/local-projects/features.lisp ]
    then
	file=$1;
	mem=`echo "scale=0;$2*1024" | bc -l`;echo $mem
	if [ -r $file ] 
	then
	    base="${file%.*}";
	    compiler=`which sbcl`; 
	    if [ -r $compiler ]; then 
		sbcl --noinform --dynamic-space-size $mem --control-stack-size 20  --load $file --eval "(save-lisp-and-die \"$base\" :executable t :save-runtime-options t :toplevel 'main)"
	    else "SBCL  not found. Please, install it first"; 
	    fi
	else
	    echo "$file not found"
	fi
    else
	echo "Files features.asd or features.lisp not found in ~/quicklisp/local-projects/"
	echo "Copy both to ~/quicklisp/local-projects/ and try to compile again."
    fi
else
    echo "Please, pass the file name and max memory alocation in gigabytes as parameters"
    echo "For instance: ./compile genppi.lisp 16"
fi
