#!/bin/bash -
if [ $# -gt 0 ]
then
    file=$1;
    if [ -r $file ] 
    then
	base="${file%.*}";
	compiler=`which sbcl`; 
	if [ -r $compiler ]; then 
	    sbcl --noinform --dynamic-space-size 4096 --control-stack-size 20  --load $file --eval "(save-lisp-and-die \"$base\" :executable t :save-runtime-options t :toplevel 'main)"
	else "SBCL  not found. Please, install it first"; 
	fi
    else
	echo "$file not found"
    fi
else
    echo "Please, pass the file name as a parameter"
fi
