name: Lisp CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-build:
    if: contains(github.event.head_commit.message, 'COMPILEWIN') || contains(github.event.head_commit.message, 'COMPILEALL')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SBCL
        run: choco install sbcl

      - name: Setup Quicklisp
        run: |
          Invoke-WebRequest -Uri https://beta.quicklisp.org/quicklisp.lisp -OutFile quicklisp.lisp
          sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install)"

      - name: Cache Quicklisp packages
        uses: actions/cache@v4
        with:
          path: $env:USERPROFILE\quicklisp\
          key: ${{ runner.os }}-quicklisp-${{ hashFiles('**/*.asd', '**/*.lisp') }}
          restore-keys: |
            ${{ runner.os }}-quicklisp-

      - name: Move Lisp files to Quicklisp local-projects directory
        run: |
          New-Item -ItemType Directory -Force -Path $env:USERPROFILE\quicklisp\local-projects
          Copy-Item src\features.asd,src\features.lisp -Destination $env:USERPROFILE\quicklisp\local-projects

      - name: Register local projects with Quicklisp
        run: |
          sbcl --non-interactive --load "$env:USERPROFILE\quicklisp\setup.lisp" --eval "(ql:register-local-projects)" --eval "(quit)"

      - name: Clean binaries directory
        run: |
          if (Test-Path binaries) { Remove-Item -Recurse -Force binaries }
          New-Item -ItemType Directory -Force -Path binaries

      - name: Build and save all executables
        run: |
          sbcl --noinform --dynamic-space-size 4096 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppi.lisp `
            --eval "(save-lisp-and-die \"binaries/genppi4g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 8192 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppi.lisp `
            --eval "(save-lisp-and-die \"binaries/genppi8g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 16384 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppi.lisp `
            --eval "(save-lisp-and-die \"binaries/genppi16g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 32768 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppi.lisp `
            --eval "(save-lisp-and-die \"binaries/genppi32g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 4096 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppidb.lisp `
            --eval "(save-lisp-and-die \"binaries/genppidb4g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 8192 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppidb.lisp `
            --eval "(save-lisp-and-die \"binaries/genppidb8g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 16384 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppidb.lisp `
            --eval "(save-lisp-and-die \"binaries/genppidb16g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"
          sbcl --noinform --dynamic-space-size 32768 --control-stack-size 20 `
            --load "$env:USERPROFILE\quicklisp\setup.lisp" `
            --load src/genppidb.lisp `
            --eval "(save-lisp-and-die \"binaries/genppidb32g-Win.exe\" :executable t :save-runtime-options t :toplevel 'main)"

      - name: Archive Windows binaries
        run: |
          Compress-Archive -Path binaries\* -DestinationPath genppi-win-binaries.zip

      - name: Upload Windows binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: genppi-win-binaries
          path: genppi-win-binaries.zip
